[package]
name = "chessground"
version = "0.4.0" # remember to update html_root_url
description = "A chessboard widget for Relm/GTK"
repository = "https://github.com/niklasf/rust-chessground"
readme = "README.md"
license = "GPL-3.0+"
authors = ["Niklas Fiekas <niklas.fiekas@backscattering.de>"]
categories = ["games", "gui"]
keywords = ["chess"]

[dependencies]
option-filter = "1.0"
gtk = "0.3.0"
gdk = "0.7.0"
cairo-rs = "0.3.0"
rsvg = "0.3.0"
time = "0.1"
relm = "0.11"
relm-derive = "0.11"
shakmaty = "0.4"

[dev-dependencies]
rand = "0.3"
relm-attributes = "0.11"
