[package]
name = "chessground"
version = "0.1.0"
description = "A chessboard widget for Relm/GTK"
repository = "https://github.com/niklasf/rust-chessground"
readme = "README.md"
license = "GPL-3.0+"
authors = ["Niklas Fiekas <niklas.fiekas@backscattering.de>"]
categories = ["games", "gui"]
keywords = ["chess"]

[dependencies]
option-filter = "1.0"
gtk = "0.2.0"
gdk = "0.6.0"
cairo-rs = "0.2.0"
rsvg = "0.2.0"
time = "0.1"
rand = "0.3"
relm = "0.10"
relm-derive = "0.10"
relm-attributes = "0.10"
shakmaty = "0.0.7"

[badges]
travis-ci = { repository = "rust-chessground", branch = "master" }
